### ISSUE TITLE
License

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/examples#1]
현재 Manany Harmony Project는 MIT License 를 채택하였는데, 다른 것들은 어떻게 해야 할까요?
레포트의 경우 지극히 개인적인 저작물이므로 CCL, MIT, GNU 아무거나 달아도 될 것 같습니다만,
시험범위 정리 문서의 경우 수업 내용과 교재의 내용이 포함되기 때문에 신중해야 할 것 같습니다.

**Comment by evenharder** [comment]
전 이 프로젝트를 언젠간 공개할 심산으로 MIT License를 단 거긴 한데(그래서 가급적 직접 만든 거고, Wikipedia에 널려 있는 CCL을 피해서 Public Domain을 찾은 거죠), 업로드를 미룬 이유 중 하나가 사실 이 License 문제 때문이었습니다. 물론, 언젠가는 짚고 넘어가야 할 문제이긴 했죠. 까다롭지만, 무시할 수는 없으니까요. License에 관한 제 의견은 다음과 같습니다.
- 각 프로젝트마다 license를 따로 정할 수도 있겠지만, gshslatexintro/example/ 에 있는 모든 프로젝트에 통용될 수 있는 상위 license가 필요하지 않을까요?
- 레포트 같은 경우는 저작권이 보통 저작자의 생각와 **사용한 저작물의 license**를 따라가는 것 같습니다. 보통 그림 같은 걸 넣으니까, 아무래도 그림의 저작권을 따라가야 하지 않을까요? 물론 이러면 각 프로젝트마다 license가 들쑥날쑥하게 될 거고, 이 우려는 결국 첫 번째 의견으로 이어지게 되죠.
- 알다시피 교재들은 저작권에 매우 민감하죠. Science Research Writing에 있는 저작권 관련 구절만 봐도 그러니까요. (이 구절도 벌써 reproduced in electronic form에 해당되려나요.)

> All rights reserved. This book, or parts thereof, may not be reproduced in any form or by any means, electronic or mechanical, including photocopying, recording or any information storage and retrieval system now known or to be invented, without written permission from the Publisher.
- 그래서 시험범위 정리 문서의 경우에는 출판사에 물어보는 게 저작권에서 확실해질 수 있는 유일한 방법일 것 같네요. 출판사가 이런 곳에 claim을 걸지는 않겠지만 그래도 저작권은 신경써야 하니까요.
- 그런 관점에서 사실 선형대수학 정리문서에 CCL 4.0 International License을 달 수 있는지 의문이에요. 물론 수학 쪽 정리 그 자체는 Public Domain에 놓여 있지만 책은 그걸 organize한 것에 저작권이 있다고 주장할 수도 있으니까요.

확실한 건 example들이 더 추가되기 전에 규범이 만들어져야 한다는 겁니다.

**Comment by seungwonpark** [comment]
그러네요. 시험범위 정리 문서는 reproduced in electronic form 에 해당하니 위험할 것 같습니다. 특히, 선형대수학 정리문서에 CCL이 달려있는 것은 서둘러 수정해야 하겠습니다. 어차피 우리가 이 repository에서 공유하려는 것은 실제 문서의 내용보다는 어떻게 그것을 formatting 하였느냐 하는 것이기 때문에, 문서 내용만 dummy text(Lorem Ipsum 등) 으로 대체하는 방법이 좋을 것 같습니다.

일단은 그 작업이 완료되기 전까지는, 해당 문서들을 repository에서 숨겨놓는 것은 어떨까요...

참고로 제가 작성한 두 개의 레포트(고급물리학, 미적분학I)들은 모두 100% 저의 저작물입니다. 따라서 어떤 license 를 사용하더라도 괜찮을 것 같습니다.

**Comment by seungwonpark** [comment]
논의의 편의를 위해 이 repository 에 있는 문서들의 목록을 정리해 둡니다.
- 시험범위 정리 문서

2015_Science_Research_Writing
2016_GSHS_Linear_Algebra_midterm
Korean_and_Life_14041
- 개인 레포트

Advanced_Physics_14041
Calculus_Prob_14041
Discrete_Data_Prob_14080
- 프로젝트

Manany_Harmony_Project
- 기타

sample_document

**Comment by seungwonpark** [comment]
우선 책과의 내용이 가장 유사하며, 출판사 또한 저작권에 매우 민감하여 선형대수학 시험범위 정리노트의 Terminology 를 제외한 부분을 Lorem Ipsum 처리하였습니다. 
1e7478cc0eeef6e2cbc4dfc97d73118dbf5d94a9
cae80720f34ad786d8c7209516445ecbd3156dfa

**Comment by seungwonpark** [comment]
곧 latex.gs.hs.kr 이 신설될 예정입니다. 저작권에 민감한 자료들을 그곳에 올리고 접근 권한을 설정해 놓으면 될 것 같습니다.

**Comment by seungwonpark** [comment]
혼동을 막기 위해 상황을 clarify 하겠습니다.
저작권 침해를 우려하여 2016_Linear_Algebra 를 Lorem Ipsum 처리했었는데, 그 이후 이것을 원상 복구했습니다.

학생들 사이의 스터디 자료 및 족보는 교육용이고, 여기 올라와 있는 자료 모두 나름대로 2차 저작물이기 때문에 저작권 침해에 해당되지 않을 것으로 보입니다.

원래는 latex.gs.hs.kr 개설 이후, 송죽학사 로그인 API로 인증받아 파일을 다운받는 형식으로 하려고 했지만, 현행대로리면 GitHub에서 이 레포지토리를 Private하게 만들어야 하고, 그에 따른 비용이 발생할 것으로 보여 포기했습니다.

혹시라도 나중에 저작권 침해와 관련된 항의가 들어올 경우 우리는 최대한 변론을 하는 것으로 하고, 그 때 가서 이 문제를 재논의하는것으로 결정짓겠습니다. 이만 이 이슈를 매듭지으려 합니다.
