### ISSUE TITLE
2017_matplot : Missing pdf image files

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/examples#2]
(2017_matplot 폴더, d77dd8ccf285746c2e7e4663fb790b921f7c83c1 커밋을 기준으로 작성된 글입니다.)

현재 images 폴더 내에, figure_1.pdf, figure_2.pdf, ... , figure_6.pdf 이 빠져 있습니다.
최상위 디렉토리의 .gitignore에 **/*.pdf 가 있기 때문에, .gitignore에 예외를 주어야 합니다.

https://github.com/gshslatexintro/examples/blob/master/Manany_Harmony_Project/.gitignore

위 링크처럼, 해당 폴더 안에서 또 .gitignore를 만들고 내용을
```
!figure_1.pdf
!figure_2.pdf
!figure_3.pdf
!figure_4.pdf
!figure_5.pdf
!figure_6.pdf
```
와 같이 `!파일명` 형식으로 적어 주면 해당 폴더 안에서만 .gitignore에 예외가 적용됩니다.

**Comment by seungwonpark** [comment]
@WoolSeo

**Comment by WoolSeo** [comment]
아.... 내가 나이가 들어가나보다
예전엔 이런거 잘 따라갔는데... 요즘에 깃허브를 볼 때마다 어렵다고 느끼는 나 자신이 ㅠㅠ ㅠㅠ
아~~~~~ ㅋㅋ

저녁에 수정해두지요 ^^

**Comment by seungwonpark** [comment]
gitignore만 수정되고 pdf 이미지 파일들은 아직 올라오지 않았습니다. 다시 확인 부탁드립니다.
